INSERT INTO CURRENCY_EXCHANGE (FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, ENVIRONMENT ) VALUES ('USD', 'INR', 65, '');
INSERT INTO CURRENCY_EXCHANGE (FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, ENVIRONMENT ) VALUES ('EUR', 'INR', 75, '');
INSERT INTO CURRENCY_EXCHANGE (FROM_CURRENCY, TO_CURRENCY, CONVERSION_MULTIPLE, ENVIRONMENT ) VALUES ('AUD', 'INR', 25, '');